import dotenv from "dotenv"
dotenv.config()

export const ENV = {
PORT : process.env.PORT,
NODE_ENV :process.env.NODE_ENV,
DB_URL : process.env.DB_URL,
BACKEND_API_URL : process.env.BACKEND_API_URL,
CLERK_PUBLISHABLE_KEY:process.env.CLERK_PUBLISHABLE_KEY,
INNGEST_SIGNING_KEY :process.env.INNGEST_SIGNIN_KEY,
CLOUDINARY_API_SECRET_KEY:process.env.CLOUDINARY_API_SECRET_KEY,
CLOUDINARY_API_KEY:process.env.CLOUDINARY_API_KEY,
CLOUDINARY_CLOUD_NAME:process.env.CLOUDINARY_CLOUD_NAME,
}